server:
  port: 8080
spring:
  application:
    name: feign-consumer  # 微服务名称
feign:
  client:
    config:
      default:
        connectTimeout: 5000   # 设置Feign客户端连接提供者的超时时限
        readTimeout: 5000  # 设置Feign从请求发出到接收到提供者的响应，这段时间的超时时限
#    url: http://127.0.0.1:8081   #客户端提供feign服务ip
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true #偏好使用ip地址，而不是host主机名
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${eureka.instance.ip-address}.${server.port}


feign-provider: # 服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 选择负载均衡策略，默认为轮询方式，当前配置为随机方式
    ConnectTimeout: 250                 # 连接超时时间
    ReadTimeout: 1000                   # ribbon 读取超时时间
    OkToRetryOnAllOperations: true      # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1         # 切换实例的重试次数
    MaxAutoRetries: 1                   # 对当前实例的重试次数